services:
  - type: web
    name: spicygames-forum
    env: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Exemple si tu veux forcer un chemin SQLite custom
      # - key: DB_PATH
      #   value: ./database.sqlite
